/*
 * SDCardCMD.h
 *
 * Created: 08.05.2021 12:11:06
 *  Author: dominik hellhake
 */ 
#ifndef SDCARDCMD_H_
#define SDCARDCMD_H_

#define SD_CMD_INIT (HSMCI_CMDR_RSPTYP_NORESP | HSMCI_CMDR_SPCMD_INIT | HSMCI_CMDR_OPDCMD_OPENDRAIN)
#define SD_CMD0 (HSMCI_CMDR_CMDNB(0) | HSMCI_CMDR_OPDCMD_OPENDRAIN)
#define SD_CMD2 (HSMCI_CMDR_CMDNB(2) | HSMCI_CMDR_RSPTYP_136_BIT | HSMCI_CMDR_OPDCMD_OPENDRAIN | HSMCI_CMDR_MAXLAT)
#define SD_CMD3 (HSMCI_CMDR_CMDNB(3) | HSMCI_CMDR_RSPTYP_48_BIT | HSMCI_CMDR_OPDCMD_OPENDRAIN | HSMCI_CMDR_MAXLAT)
#define SD_CMD4 (HSMCI_CMDR_CMDNB(4))
#define SD_CMD7 (HSMCI_CMDR_CMDNB(7) | HSMCI_CMDR_RSPTYP_R1B | HSMCI_CMDR_MAXLAT)
#define SD_CMD8 (HSMCI_CMDR_CMDNB(8) | HSMCI_CMDR_RSPTYP_48_BIT | HSMCI_CMDR_OPDCMD_OPENDRAIN | HSMCI_CMDR_MAXLAT)
#define SD_CMD9 (HSMCI_CMDR_CMDNB(9) | HSMCI_CMDR_RSPTYP_136_BIT | HSMCI_CMDR_MAXLAT)
#define SD_CMD12 (HSMCI_CMDR_CMDNB(12) | HSMCI_CMDR_RSPTYP_48_BIT | HSMCI_CMDR_MAXLAT)
#define SD_CMD13 (HSMCI_CMDR_CMDNB(13) | HSMCI_CMDR_RSPTYP_48_BIT | HSMCI_CMDR_MAXLAT)
#define SD_CMD16 (HSMCI_CMDR_CMDNB(16) | HSMCI_CMDR_RSPTYP_48_BIT | HSMCI_CMDR_MAXLAT)
#define SD_CMD17 (HSMCI_CMDR_CMDNB(17) | HSMCI_CMDR_RSPTYP_48_BIT | HSMCI_CMDR_MAXLAT | HSMCI_CMDR_TRCMD_START_DATA | HSMCI_CMDR_TRDIR_READ | HSMCI_CMDR_TRTYP_SINGLE)
#define SD_CMD24 (HSMCI_CMDR_CMDNB(24) | HSMCI_CMDR_RSPTYP_48_BIT | HSMCI_CMDR_MAXLAT | HSMCI_CMDR_TRCMD_START_DATA | HSMCI_CMDR_TRDIR_WRITE | HSMCI_CMDR_TRTYP_SINGLE)
#define SD_CMD25 (HSMCI_CMDR_CMDNB(25) | HSMCI_CMDR_RSPTYP_48_BIT | HSMCI_CMDR_MAXLAT | HSMCI_CMDR_TRCMD_START_DATA | HSMCI_CMDR_TRDIR_WRITE | HSMCI_CMDR_TRTYP_MULTIPLE)
#define SD_CMD55 (HSMCI_CMDR_CMDNB(55) | HSMCI_CMDR_RSPTYP_48_BIT | HSMCI_CMDR_MAXLAT)
#define SD_ACMD41 (HSMCI_CMDR_CMDNB(41) | HSMCI_CMDR_RSPTYP_48_BIT | HSMCI_CMDR_OPDCMD_OPENDRAIN | HSMCI_CMDR_MAXLAT)
#define SD_ACMD6 (HSMCI_CMDR_CMDNB(6) | HSMCI_CMDR_RSPTYP_48_BIT | HSMCI_CMDR_MAXLAT)


#endif /* SDCARDCMD_H_ */